--- 
App: 
  :bg_color:
    - 30
    - 30
    - 30
    - 255
Label: 
  :font: Vera.ttf
  :font_size: 20
  :color:
    - 255
    - 255
    - 255
    - 255
  :bg_color:
    - 30
    - 30
    - 230
    - 255
  :border:
    - 130
    - 250
    - 230
    - 255
Button: 
  :font: Vera.ttf
  :font_size: 20
  :color:
    - 255
    - 255
    - 255
    - 255
  :bg_color:
    - 130
    - 30
    - 30
    - 255
  :border:
    - 130
    - 250
    - 230
    - 255
