--- 
Rubygoo::App: # look at Rubygoo::CssColors for list
  :bg_color: :Snow
Rubygoo::Container: 
  :bg_color: :Silver
Rubygoo::Widget: # fonts should live in the theme's dir
  :font: Vera.ttf
  :font_size: 20
  :color: :Tomato
  :focus_color: :LightSlateGray
  :bg_color: :WhiteSmoke
  :disabled_color: :WhiteSmoke
  :border_color: :DarkSlateBlue
  :hover_color: # can specify a color by r,g,b,a as well
   - 55
   - 55
   - 55
   - 150
Rubygoo::Button: 
  :bg_color: :LightGray
Rubygoo::CheckBox:
  :checked_color: :LightSlateGray
Rubygoo::TextField:
  :fg_color: :Black
  :bg_color: :Silver
  :bg_select_color: :DarkSlateBlue
  :fg_select_color: :Snow
  :border_color: :DarkSlateBlue
Rubygoo::MouseCursor:
  :color: :DarkSlateGray
  :mouse_cursor: cursor.png
