--- 
App: 
  :bg_color: :Black
Widget: 
  :font: Vera.ttf
  :font_size: 20
  :color: :Black
  :focus_color: :FireBrick
  :bg_color: :Gray
  :border_color: :FireBrick
Button: 
  :bg_color: :DimGray
CheckBox:
  :checked_color: :FireBrick
TextField:
  :fg_color: :FireBrick
  :bg_color: :Gray
  :bg_select_color: :FireBrick
  :fg_select_color: :Snow
  :border_color: :Black
MouseCursor:
  :color: :Snow
  :mouse_cursor: cursor.png
